import tensorflow as tf;
import tflearn as tfl;
from bn import batch_norm;
from bn import instance_norm;
def PlainCNN_Bn(dev,sizes):
    net = {};
    batch_size = sizes[0];
    h = sizes[1];
    w = sizes[2];
    img = tf.placeholder(dtype=tf.float32,shape=[None,h,w,3],name="img");
    istrain = tf.placeholder(dtype=tf.bool,shape=[],name="train_condition");
    net["img"] = img;
    net["istrain"] = istrain;
    x = tfl.layers.conv.conv_2d(img,16,(7,7),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = batch_norm(x,istrain,name="bn00");
    x = tf.nn.relu(x);
    net["conv00"] = x;
    x = tfl.layers.conv.conv_2d(  x,16,(7,7),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = batch_norm(x,istrain,name="bn01");
    x = tf.nn.relu(x);
    net["conv01"] = x;
    x = tfl.layers.conv.conv_2d(  x,32,(7,7),strides=4,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = batch_norm(x,istrain,name="bn02");
    x = tf.nn.relu(x);
    net["conv02"] = x;
    i = 3;
    ch = 32;
    while x.shape[1] > 2 and x.shape[2] > 2:
        x = tfl.layers.conv.conv_2d(x,ch,(3,3),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = batch_norm(x,istrain,name="bn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        x = tfl.layers.conv.conv_2d(x,ch,(3,3),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = batch_norm(x,istrain,name="bn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        x = tfl.layers.conv.conv_2d(x,2*ch,(3,3),strides=2,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = batch_norm(x,istrain,name="bn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        if ch < 512 :
            ch *= 2;
    x = tfl.layers.core.fully_connected(x,128,activation='relu',weight_decay=1e-4,regularizer='L2');
    net["fc%02d"%i] = x;
    i += 1;
    x = tfl.layers.core.fully_connected(x,22,activation='linear',weight_decay=1e-4,regularizer='L2');
    net["fc%02d"%i] = x;
    net["out"] = x;
    i += 1;
    return net;

def PlainCNN_Instn(dev,sizes):
    net = {};
    batch_size = sizes[0];
    h = sizes[1];
    w = sizes[2];
    img = tf.placeholder(dtype=tf.float32,shape=[None,h,w,3],name="img");
    net["img"] = img;
    x = tfl.layers.conv.conv_2d(img,16,(7,7),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = instance_norm(x,name="Instn00");
    x = tf.nn.relu(x);
    net["conv00"] = x;
    x = tfl.layers.conv.conv_2d(  x,16,(7,7),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = instance_norm(x,name="Instn01");
    x = tf.nn.relu(x);
    net["conv01"] = x;
    x = tfl.layers.conv.conv_2d(  x,32,(7,7),strides=4,activation='linear',weight_decay=1e-5,regularizer='L1');
    x = instance_norm(x,name="Instn02");
    x = tf.nn.relu(x);
    net["conv02"] = x;
    i = 3;
    ch = 32;
    while x.shape[1] > 2 and x.shape[2] > 2:
        x = tfl.layers.conv.conv_2d(x,ch,(3,3),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = instance_norm(x,name="Instn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        x = tfl.layers.conv.conv_2d(x,ch,(3,3),strides=1,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = instance_norm(x,name="Instn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        x = tfl.layers.conv.conv_2d(x,2*ch,(3,3),strides=2,activation='linear',weight_decay=1e-5,regularizer='L1');
        x = instance_norm(x,name="Instn%02d"%i);
        x = tf.nn.relu(x);
        net["conv%02d"%i] = x;
        i += 1;
        if ch < 512 :
            ch *= 2;
    x = tfl.layers.core.fully_connected(x,128,activation='relu',weight_decay=1e-4,regularizer='L2');
    net["fc%02d"%i] = x;
    i += 1;
    x = tfl.layers.core.fully_connected(x,22,activation='linear',weight_decay=1e-4,regularizer='L2');
    net["fc%02d"%i] = x;
    net["out"] = x;
    i += 1;
    return net;